#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x41633B9FE837F581 (vapier@gentoo.org)
#
Name     : attr
Version  : 2.4.48
Release  : 38
URL      : http://download-mirror.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz
Source0  : http://download-mirror.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz
Source99 : http://download-mirror.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz.sig
Summary  : A library for filesystem extended attribute support
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.1
Requires: attr-bin
Requires: attr-lib
Requires: attr-license
Requires: attr-locales
Requires: attr-man
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
Patch1: 0001-attr-2.4.48-test-suite-perl.patch
Patch2: 0002-attr-2.4.48-switch-back-to-syscall.patch

%description
_________________________________
Package home: http://savannah.nongnu.org/projects/attr

%package bin
Summary: bin components for the attr package.
Group: Binaries
Requires: attr-license = %{version}-%{release}
Requires: attr-man = %{version}-%{release}

%description bin
bin components for the attr package.


%package dev
Summary: dev components for the attr package.
Group: Development
Requires: attr-lib = %{version}-%{release}
Requires: attr-bin = %{version}-%{release}
Provides: attr-devel = %{version}-%{release}

%description dev
dev components for the attr package.


%package dev32
Summary: dev32 components for the attr package.
Group: Default
Requires: attr-lib32 = %{version}-%{release}
Requires: attr-bin = %{version}-%{release}
Requires: attr-dev = %{version}-%{release}

%description dev32
dev32 components for the attr package.


%package doc
Summary: doc components for the attr package.
Group: Documentation
Requires: attr-man = %{version}-%{release}

%description doc
doc components for the attr package.


%package lib
Summary: lib components for the attr package.
Group: Libraries
Requires: attr-license = %{version}-%{release}

%description lib
lib components for the attr package.


%package lib32
Summary: lib32 components for the attr package.
Group: Default
Requires: attr-license = %{version}-%{release}

%description lib32
lib32 components for the attr package.


%package license
Summary: license components for the attr package.
Group: Default

%description license
license components for the attr package.


%package locales
Summary: locales components for the attr package.
Group: Default

%description locales
locales components for the attr package.


%package man
Summary: man components for the attr package.
Group: Default

%description man
man components for the attr package.


%prep
%setup -q -n attr-2.4.48
%patch1 -p1
%patch2 -p1
pushd ..
cp -a attr-2.4.48 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1536948634
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-semantic-interposition "
%configure --disable-static INSTALL_USER=root \
INSTALL_GROUP=root \
--enable-nls \
--enable-shared \
--disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static INSTALL_USER=root \
INSTALL_GROUP=root \
--enable-nls \
--enable-shared \
--disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1536948634
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/attr
cp doc/COPYING %{buildroot}/usr/share/doc/attr/doc_COPYING
cp doc/COPYING.LGPL %{buildroot}/usr/share/doc/attr/doc_COPYING.LGPL
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
%find_lang attr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/attr
/usr/bin/getfattr
/usr/bin/setfattr

%files dev
%defattr(-,root,root,-)
/usr/include/attr/attributes.h
/usr/include/attr/error_context.h
/usr/include/attr/libattr.h
/usr/lib64/libattr.so
/usr/lib64/pkgconfig/libattr.pc
/usr/share/man/man3/attr_get.3
/usr/share/man/man3/attr_getf.3
/usr/share/man/man3/attr_list.3
/usr/share/man/man3/attr_listf.3
/usr/share/man/man3/attr_multi.3
/usr/share/man/man3/attr_multif.3
/usr/share/man/man3/attr_remove.3
/usr/share/man/man3/attr_removef.3
/usr/share/man/man3/attr_set.3
/usr/share/man/man3/attr_setf.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libattr.so
/usr/lib32/pkgconfig/32libattr.pc
/usr/lib32/pkgconfig/libattr.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/attr/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libattr.so.1
/usr/lib64/libattr.so.1.1.2448

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libattr.so.1
/usr/lib32/libattr.so.1.1.2448

%files license
%defattr(-,root,root,-)
/usr/share/doc/attr/COPYING
/usr/share/doc/attr/COPYING.LGPL
/usr/share/doc/attr/doc_COPYING
/usr/share/doc/attr/doc_COPYING.LGPL

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/attr.1
/usr/share/man/man1/getfattr.1
/usr/share/man/man1/setfattr.1

%files locales -f attr.lang
%defattr(-,root,root,-)

