#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x41633B9FE837F581 (vapier@gentoo.org)
#
Name     : attr
Version  : 2.4.48
Release  : 40
URL      : https://download-mirror.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz
Source0  : https://download-mirror.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz
Source1 : https://download-mirror.savannah.gnu.org/releases/attr/attr-2.4.48.tar.gz.sig
Summary  : A library for filesystem extended attribute support
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.1
Requires: attr-bin = %{version}-%{release}
Requires: attr-lib = %{version}-%{release}
Requires: attr-license = %{version}-%{release}
Requires: attr-locales = %{version}-%{release}
Requires: attr-man = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
Patch1: 0001-attr-2.4.48-test-suite-perl.patch
Patch2: 0002-attr-2.4.48-switch-back-to-syscall.patch

%description
_________________________________
Package home: http://savannah.nongnu.org/projects/attr

%package bin
Summary: bin components for the attr package.
Group: Binaries
Requires: attr-license = %{version}-%{release}

%description bin
bin components for the attr package.


%package dev
Summary: dev components for the attr package.
Group: Development
Requires: attr-lib = %{version}-%{release}
Requires: attr-bin = %{version}-%{release}
Provides: attr-devel = %{version}-%{release}
Requires: attr = %{version}-%{release}

%description dev
dev components for the attr package.


%package dev32
Summary: dev32 components for the attr package.
Group: Default
Requires: attr-lib32 = %{version}-%{release}
Requires: attr-bin = %{version}-%{release}
Requires: attr-dev = %{version}-%{release}

%description dev32
dev32 components for the attr package.


%package doc
Summary: doc components for the attr package.
Group: Documentation
Requires: attr-man = %{version}-%{release}

%description doc
doc components for the attr package.


%package lib
Summary: lib components for the attr package.
Group: Libraries
Requires: attr-license = %{version}-%{release}

%description lib
lib components for the attr package.


%package lib32
Summary: lib32 components for the attr package.
Group: Default
Requires: attr-license = %{version}-%{release}

%description lib32
lib32 components for the attr package.


%package license
Summary: license components for the attr package.
Group: Default

%description license
license components for the attr package.


%package locales
Summary: locales components for the attr package.
Group: Default

%description locales
locales components for the attr package.


%package man
Summary: man components for the attr package.
Group: Default

%description man
man components for the attr package.


%prep
%setup -q -n attr-2.4.48
%patch1 -p1
%patch2 -p1
pushd ..
cp -a attr-2.4.48 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568830021
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition "
%configure --disable-static INSTALL_USER=root \
INSTALL_GROUP=root \
--enable-nls \
--enable-shared \
--disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static INSTALL_USER=root \
INSTALL_GROUP=root \
--enable-nls \
--enable-shared \
--disable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || : || :

%install
export SOURCE_DATE_EPOCH=1568830021
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/attr
cp doc/COPYING %{buildroot}/usr/share/package-licenses/attr/doc_COPYING
cp doc/COPYING.LGPL %{buildroot}/usr/share/package-licenses/attr/doc_COPYING.LGPL
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
%find_lang attr
## Remove excluded files
rm -f %{buildroot}/usr/share/man/man5/attr.5

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/attr
/usr/bin/getfattr
/usr/bin/setfattr

%files dev
%defattr(-,root,root,-)
/usr/include/attr/attributes.h
/usr/include/attr/error_context.h
/usr/include/attr/libattr.h
/usr/lib64/libattr.so
/usr/lib64/pkgconfig/libattr.pc
/usr/share/man/man3/attr_get.3
/usr/share/man/man3/attr_getf.3
/usr/share/man/man3/attr_list.3
/usr/share/man/man3/attr_listf.3
/usr/share/man/man3/attr_multi.3
/usr/share/man/man3/attr_multif.3
/usr/share/man/man3/attr_remove.3
/usr/share/man/man3/attr_removef.3
/usr/share/man/man3/attr_set.3
/usr/share/man/man3/attr_setf.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libattr.so
/usr/lib32/pkgconfig/32libattr.pc
/usr/lib32/pkgconfig/libattr.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/attr/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libattr.so.1
/usr/lib64/libattr.so.1.1.2448

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libattr.so.1
/usr/lib32/libattr.so.1.1.2448

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/attr/doc_COPYING
/usr/share/package-licenses/attr/doc_COPYING.LGPL

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/attr.1
/usr/share/man/man1/getfattr.1
/usr/share/man/man1/setfattr.1

%files locales -f attr.lang
%defattr(-,root,root,-)

